// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO0sNO_snxt8APO7Do0mSos4UwgS5PGLk',
    appId: '1:1095111545899:web:c591be8db1ab875295866e',
    messagingSenderId: '1095111545899',
    projectId: 'crud-app-10c21',
    authDomain: 'crud-app-10c21.firebaseapp.com',
    storageBucket: 'crud-app-10c21.appspot.com',
    measurementId: 'G-VDH7GZJ9DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQKGCqTadkFtUXnGKAAv8h4GNri0S4Bk',
    appId: '1:1095111545899:android:edb27737718ffd6e95866e',
    messagingSenderId: '1095111545899',
    projectId: 'crud-app-10c21',
    storageBucket: 'crud-app-10c21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCope_bFRXGHZGLOk6dpAfhTJfOveqHYqM',
    appId: '1:1095111545899:ios:1f96b07af5ece3ea95866e',
    messagingSenderId: '1095111545899',
    projectId: 'crud-app-10c21',
    storageBucket: 'crud-app-10c21.appspot.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCope_bFRXGHZGLOk6dpAfhTJfOveqHYqM',
    appId: '1:1095111545899:ios:1f96b07af5ece3ea95866e',
    messagingSenderId: '1095111545899',
    projectId: 'crud-app-10c21',
    storageBucket: 'crud-app-10c21.appspot.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO0sNO_snxt8APO7Do0mSos4UwgS5PGLk',
    appId: '1:1095111545899:web:dbc94eb6af1eb48895866e',
    messagingSenderId: '1095111545899',
    projectId: 'crud-app-10c21',
    authDomain: 'crud-app-10c21.firebaseapp.com',
    storageBucket: 'crud-app-10c21.appspot.com',
    measurementId: 'G-58NSWBVB4M',
  );
}
